<Project>
  <Target Name="CopyNativeLib" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <None Include="$(MSBuildThisFileDirectory)win-x64/$(BaseIntermediateOutputPath)**/lsl.dll"
            Link="runtimes/win-x64/native/lsl.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>

      <None Include="$(MSBuildThisFileDirectory)win-x86/$(BaseIntermediateOutputPath)**/lsl.dll"
            Link="runtimes/win-x64/native/lsl.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
  </Target>
</Project>